spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://{DB_HOST}:{DB_PORT}/{DB_NAME}
    username: {DB_USERNAME}
    password: {DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true

server:
  port: 8081

application:
  upload-directory:
    base-url: /src/main/upload
