spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://${applicationdb.database_host}:${applicationdb.database_port}/${applicationdb.database_name}
    username: ${applicationdb.database_username}
    password: ${applicationdb.database_password}
#    driver-class-name: org.postgresql.Driver
  profile:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

application:
  upload-directory:
    base-url: /src/main/upload

applicationdb:
  database_host: localhost
  database_port: 5432
  database_name: nutech_integrasi
  database_username: postgres
  database_password: docker